<?xml version="1.0" encoding="UTF-8"?>
<module external.linked.project.id=":Topics-Array_exceptions-Out_of_bounds_:main" external.linked.project.path="$MODULE_DIR$/../../../../../Topics/Array exceptions/Out of bounds_" external.root.project.path="$MODULE_DIR$/../../../../.." external.system.id="GRADLE" external.system.module.group="Blockchain" external.system.module.type="sourceSet" external.system.module.version="unspecified" type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_11">
    <output url="file://$MODULE_DIR$/../../../../../Topics/Array exceptions/Out of bounds_/out/production/classes" />
    <exclude-output />
    <content url="file://$MODULE_DIR$/../../../../../Topics/Array exceptions/Out of bounds_/src">
      <sourceFolder url="file://$MODULE_DIR$/../../../../../Topics/Array exceptions/Out of bounds_/src" isTestSource="false" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>